### ISSUE TITLE
文章之間的關係圖（鳥瞰圖）

### ISSUE THREAD

**Issue by MROS** [carbon-bond/carbonbond#141]
- ~顯示一篇文章的相關文章~
- ~以箭頭表示鏈接~
- ~根據鍵能來決定文章的醒目程度~
- ~hover 時應該預覽文章~

**Comment by MROS** [comment]
更多功能：
- 一條以上的鍵結（美化起訖點）
- 顯示鍵結的屬性
  - 鍵能
  - 標籤

**Comment by david0u0** [comment]
儀表板
   - 以何決定大小，鍵能/鍵能絕對值/留言/...
 定位主角文章

**Comment by MROS** [comment]
力語言已簡化，鳥瞰圖的未來，往後再議
