### ISSUE TITLE
視窗縮小時，左側邊攔會固定於螢幕的左側

### ISSUE THREAD

**Issue by fro11o** [carbon-bond/carbonbond#142]
如圖
![圖片](https://user-images.githubusercontent.com/6565150/100497816-c7b12f00-3198-11eb-82af-a1e4f4103ed7.png)

**Comment by MROS** [comment]
https://github.com/carbon-bond/carbonbond/commit/afe1d8057db323ce7d7a30616a0c8987143c8bef
