### ISSUE TITLE
編輯器切換看板／分類時的幾個易用性的問題

### ISSUE THREAD

**Issue by david0u0** [carbon-bond/carbonbond#150]
1. 編輯到一半換看板的體驗不佳，會直接消除文章
2. 編輯到一半換分類的體驗不佳
    - 可以比對一下前後分類，如果一致就幫他照順序填進去
    - 如果填不進去可以問他要不要存草稿
3. 編輯中再去點鍵結，如果沒有變化，感覺全無回饋

**Comment by fro11o** [comment]
1. 2. 可向使用者詢問要不要存檔來解決

**Comment by MROS** [comment]
由於看板被編輯後，分類的欄位名稱、型別可能改變（簡稱爲格式改變）、甚至整個分類被刪除，但草稿跟以前的文章的格式並不會跟着改變，當載入到編輯器時，可能會找不到能夠匹配的分類，處理方式可分爲以下幾種方式：

1. 載入草稿，分類仍然存在，但格式已經改變
=> 顯示唯讀文本，要求選擇分類。提示一個按鈕可切換到同名分類
2. 載入草稿，分類已經不存在
=> 顯示唯讀文本，要求選擇分類
3. 編輯文章，分類仍然存在，但格式已經改變
=> 提示一個按鈕可切換到同名分類
/4. 編輯文章，分類已經不存在
=> 提示分類已經不存在，但仍可繼續使用原格式

**Comment by MROS** [comment]
切換分類的算法爲
1. 若新分類欄位爲舊分類的超集，則將各欄位一一放入新分類
2. 若新分類中有任何欄位屬性爲多行文本，把舊分類中所有不能對應的欄位全部放到該多行文本欄位中
3. 若新分類沒有欄位是多行文本，且新舊分類有不同名或不同屬性的欄位，警告使用者舊分類中的部分欄位將被丟棄
