### ISSUE TITLE
熱門看板人氣 -1 問題

### ISSUE THREAD

**Issue by MROS** [carbon-bond/carbonbond#152]

**Comment by MROS** [comment]
討論：用每日發文量來取代上線人數，也能衡量看板熱門程度，而且更動也不那麼頻繁（切換看板的請求量想必大於發文量）。

**Comment by MROS** [comment]
@fro11o 考慮有哪些指標可以衡量熱門程度，並在此討論各個指標實作的效能以及難易度。

**Comment by fro11o** [comment]
- 一個看板過去 24 小時內被多少用戶 query 過？
  - 需紀錄每個 user 最近一次點擊某看板的時間 (|user數量| * |看板數量|)
  - 每整點計算一次分數 (不同看板可錯開以避免 DB loading)
- 一個看板過去 24 小時內有多少發文？
  - 每整點計算一次分數
- 一個看板過去 24 小時內有多少留言？
  - 每整點計算一次分數

**Comment by MROS** [comment]
光是比較出排名不夠，各個看板還必須能夠顯示 24 小時內文章的數量。

**Comment by fro11o** [comment]
是說要達到 1. 2. 是不是不見得需要用到上次提到的 tree 結構，可能一個 queue 也可以，塞新的就在尾端塞，有 query 時就從頭開始檢查剔除超過 24 小時的，然後再同時維護各看板的 24 小時內文章數量。 （還是是因為無法保證 new_article 帶的時間戳進到 redis 時是遞增的，可能有時候不小心有意外導致順序錯了？）（但這種小瑕疵對於熱門看本文章數這種功能是不是無傷大雅，稍微不精確也ＯＫ）


上次還說只要用一棵樹，不要每個看板都一棵樹的理由是什麼我忘了？比較方便管理嗎？

**Comment by MROS** [comment]
對欸用 queue 更快，用樹是過度設計了。

如果有一千個看板就要維護一千棵樹，但這一千棵樹可能只有十個需要更新而已。

用 queue 的話，也是維護一個 queue 就好。

**Comment by fro11o** [comment]
但現在覺得還是可以用 redis 的 Sorted Sets 來實作，
一方面是不用把 (timestamp, 看板) 這兩個資料 encode 成 String 存入 redis 的 Lists，
這樣取出時還要 decode。
另一方面 Sorted Sets 有 `ZRANGEBYSCORE` 一次取出某分數 (timestamp) 以下的資料，
也有 `ZREMRANGEBYSCORE` 可以直接刪除一段範圍的資料。

目前預計的 key 為
- `board_24h_article_number`, Sorted Sets Type, 存某看板的 24h 內文章數, 可以查詢前 n 熱門看版
- `article_in_24h`, Sorted Sets Type, 存 24h 內新文章的 timestamp, 新增跟移除的同時去修改 `board_24h_article_number`

然後 query 看板熱度跟 query 前 n 熱門看板時，是否需要 blocking 更新完才回傳？
或是可以先用當前的 `board_24h_article_number` 的資料回覆，
背後再 fork 出來一支做更新。

**Comment by fro11o** [comment]
通常這種需要某些事情在背後自己跑的，
rust 都怎麼處理的？
是去找個類似 `nix::unistd::fork` 的套件嗎？
還是有更 modern / rust-style 的處理方式？

**Comment by MROS** [comment]
應該用不著 fork 進程，甚至不開執行緒，我們目前在用的異步運行時 tokio 可以跑協程。你需要花點時間讀一下 https://docs.rs/tokio/latest/tokio/task/index.html ，tokio 的官網有更多資訊，https://tokio.rs/

**Comment by MROS** [comment]
> 但現在覺得還是可以用 redis 的 Sorted Sets 來實作， 一方面是不用把 (timestamp, 看板) 這兩個資料 encode 成 String 存入 redis 的 Lists， 這樣取出時還要 decode。 另一方面 Sorted Sets 有 `ZRANGEBYSCORE` 一次取出某分數 (timestamp) 以下的資料， 也有 `ZREMRANGEBYSCORE` 可以直接刪除一段範圍的資料。
> 
> 目前預計的 key 為
> 
>     * `board_24h_article_number`, Sorted Sets Type, 存某看板的 24h 內文章數, 可以查詢前 n 熱門看版
> 
>     * `article_in_24h`, Sorted Sets Type, 存 24h 內新文章的 timestamp, 新增跟移除的同時去修改 `board_24h_article_number`
> 
> 
> 然後 query 看板熱度跟 query 前 n 熱門看板時，是否需要 blocking 更新完才回傳？ 或是可以先用當前的 `board_24h_article_number` 的資料回覆， 背後再 fork 出來一支做更新。

意思是說使用者並不會拿到準確的資料？如果最近24小時沒有使用者詢問看板熱度，那最新的詢問就會拿到前天的資料嗎？
