### ISSUE TITLE
討論釋出計劃

### ISSUE THREAD

**Issue by david0u0** [carbon-bond/carbonbond#156]
# 碳鍵大整理

### 文章系統
- 發文/編輯/刪除
    * 後端
    * UI
        - 鍵結、各種欄位如何讓使用者輸入，還可再設計
- 留言/編輯/刪除
    * UI
        - 留言的 UI 不該用底部編輯器
- 回文
    * UI
- 草稿
- 文章編輯與力語言修改的交互作用
    * 留言（小的）的客製化 => 光語言？

### 看板系統
- 誰有權更新力語言？如何更新？
- 看板列表
- 追蹤看板
- 看板人氣
- 熱門看板

### 通知系統
- 文章被回了
- 文章鍵能變了（有通知閾值）
- 自己被追蹤/仇視了
- 成就？

### 鍵能
- 個人鍵能
- 文章鍵能
- 公式 & 後端 & UI

### 瀏覽文章
- 分頁時的效能問題
- 留言
- 文章的回文
- 留言的留言
    * 後端
        - 優化
        - 儲存
    * UI
- __文章各欄位的呈現方式__
    * 例如：單行的陣列、數字、評分、鍵結

### 樹狀圖
- 算法
    * 做廣度優先搜索，限節點數 ？
- UI

### 搜尋
- 依作者、板、分類、時間
- 各欄位內容搜尋
- 模糊搜尋
- 上方搜尋欄應該讓人搜板

### 使用者功能
- 個人頁，包含設定
- 個板
    * 力語言模板
- 追蹤/仇視
- 成就/任務

### 行動版
- 至少看板和文章可瀏覽

### 力語言 1.1
- 陣列元素 unique 功能
    * 應用：多重鍵結時避免鍵結至同一篇
 
----

### 力語言 2.0
- 結構的陣列
- 分類族可對分類進行某些型別檢查

### 聊天

**Comment by MROS** [comment]
https://github.com/carbon-bond/carbonbond/issues/216

改以律師站爲優先考量
