### ISSUE TITLE
無限卷動和文章瀏覽的兩難

### ISSUE THREAD

**Issue by david0u0** [carbon-bond/carbonbond#157]
假如用戶卷了五分鐘看到他感興趣的文，點進去看，再出來就跑回看板最頂端，氣氣氣氣

**Comment by MROS** [comment]
瀏覽器應該會自動記錄上一頁的滾動狀態，我在猜之所以現在沒辦法自動滾，是因爲現在的滾動條是在 <div className="other"> 上，而不是在整個 html 的 body 上。

**Comment by MROS** [comment]
先用 [react-activation](https://github.com/CJY0208/react-activation)做一版，但仍不太穩定。

若想自己重新實現，可參考 https://github.com/liuye1296/react-keepAlive
