### ISSUE TITLE
前端不可變函式庫從 immer 改換成 immutable.js

### ISSUE THREAD

**Issue by david0u0** [carbon-bond/carbonbond#19]
富文本編輯器如 slate.js draft.js 皆使用 immutable.js 提供不可變性，而非我們原先選用的 immer.js

為了節省程式碼的大小，並且避免一個專案中有兩個功能重疊的函式，希望儘早將所有前端依賴換成 immutable.js

**Comment by MROS** [comment]
我重新省思一下前臺要儲存哪些數據（等聊天功能討論穩定），再一起改掉。
