### ISSUE TITLE
註冊頁面顯示服務條款超鏈接

### ISSUE THREAD

**Issue by MROS** [carbon-bond/carbonbond#245]

**Comment by fro11o** [comment]
超連結到...什麼？一個含有服務條款的視窗跳出來嗎？還是會有個網址專門顯示服務條款

**Comment by MROS** [comment]
https://www.facebook.com/legal/terms/update

可以參考臉書的註冊流程，在註冊的時候會有一行小字說當你註冊時，就代表你已經同意以上超鏈接的條款。

所以應該有兩個步驟

- 碳鍵有一頁專門放服務條款（或是丟到 github 的某一頁就好...）
- 註冊頁面有一行小字超鏈接到服務條款頁面
