### ISSUE TITLE
確認全站熱門目前的機制，並調查是否存在無法顯示之問題

### ISSUE THREAD

**Issue by fro11o** [carbon-bond/carbonbond#294]

**Comment by MROS** [comment]
之前 dev 曾經發生過全站熱門無法顯示的問題，調查並修復看看

**Comment by fro11o** [comment]
log_10(z) + article_create_timestamp / 45000, where z = max(鍵能, 1) 
redis 中維護一個 sorted set，
目前只有 `set_hot_article_score` 會在文章初次產生時計算一個分數。
而 `set_hot_article_score` 原先是要在當文章鍵能被修改時，更新 redis 中的分數，
但目前沒有任何地方會呼叫到這個函式。
另外 `search_pop_article` 會被 `SearchPopArticle` 所呼叫，目前只會固定要 10 筆資料。

**Comment by fro11o** [comment]
#186

**Comment by fro11o** [comment]
可參考 #186

**Comment by MROS** [comment]
確保 redis 使用的記憶體不無限增長

**Comment by fro11o** [comment]
目前 redis 中有下列 key
- <user_id>, Strings TYPE, 當 query_board / query_board_by_id 時會儲存某 user_id 在看哪個板
- boards, Hashes TYPE, 儲存某看板的的人氣
- hot_boards, Lists TYPE, 透過 redis boards 中的資料取前幾名，存入 hot_boards (目前 MAX_HOT_BOARDS = 100)
- 好像還有紀錄 token -> user_id 的對應

原本有還有 article_energy 這個 key，但預計會拿掉不把 energy 存在 redis 中，而是未來呼叫 modify_article_energy 的人直接帶入。
所以除了 user_id 爆量或是看板數量爆量，應該不存在 redis 記憶體吃光的可能。

**Comment by MROS** [comment]
但我們現在應該會把 user_id 從 redis 裡拔掉？因爲我們現在沒有要儲存看板人氣了

**Comment by fro11o** [comment]
對，之後新的熱度計算方式不需要這個資訊
