### ISSUE TITLE
政黨的權力分配使用「身份組」或是「階層制」

### ISSUE THREAD

**Issue by MROS** [carbon-bond/carbonbond#44]
討論權力分配應該使用

- 身份組（類似 discord）
- 階層制（類似 facebook）

以下是政黨擁有的權力。權力後面的數字代表第幾階層（數字越大，越高階）的人才能行使。這些數字是石墨的提案。

（身份組則交由黨主席自行分配，亦可預設幾個易用的身份組）

### 對看板

- 刪文 1
- 置頂文章 2
- 打 hashtag 1
- 噤聲 1
- 奪權 3
- 看版設定
  - 簡單
    - 基本介紹 2
    - 推薦外掛 2
  - 高級
    - 分類 2

### 對黨內

- 加人／踢人 2
- 權力分配 3
- 黨內設定（介紹） 2
- 創版 3
- 出走 3

**Comment by liu115** [comment]
投票決定用身份組，開版預設階層的身份組
