### ISSUE TITLE
統一錯誤碼

### ISSUE THREAD

**Issue by MROS** [carbon-bond/carbonbond#55]
`custom_error.rs` 中的 `LogicError` 中有一個 `key` 欄位，需要文件／註解定義 key 的數值代表的含義。

**Comment by jerry73204** [comment]
我個人比較主張之前提出的方式
定義不同的 error struct 或 enum
再全部打包成 logic error
錯誤碼就跟着 error struct/enum 走

**Comment by MROS** [comment]
那這樣前後端的 enum 要共享，需要用一個 config 檔案來生成？

**Comment by MROS** [comment]
開會討論決議爲：

先將 LogicError 中的 msg, key 改爲一個 enum 。暫時不自動生成程式碼，手動規範前後端的錯誤碼一致性。
