### ISSUE TITLE
id -> name 混淆

### ISSUE THREAD

**Issue by MROS** [carbon-bond/carbonbond#57]
在 PR #45 中，有許多應該回傳 name 而非 id 的 API，被回傳成了 id ，使得在使用者介面上只能看到 id （沒意義的數字）。

由於 user 的主鍵被更改，graphQL 中出現 user_id 的地方應該都改爲 User 這個 type ，以便於同時取得 id 以及 name 。

**Comment by jerry73204** [comment]
我希望在 @david0u0 的東西進去後一起處理

**Comment by MROS** [comment]
不重要了，將遷至幾丁質
