### ISSUE TITLE
回文功能

### ISSUE THREAD

**Issue by david0u0** [carbon-bond/carbonbond#6]
回文功能應整合於右下的編輯器面板，用以回應一至多篇文章。

應以易懂的UI顯示當前的回文欲創建哪些鍵結、也要可以調整是`挺`還是`鬥`。

上述資訊將傳回後端，並確實更新資料庫。

建立鍵結時，前後端必需進行檢查：
* 鍵結能否輸能？
    - 根據分類的 transfusable 欄位
* 鍵結能否指向欲回應的分類？
    - 根據分類的 attach_to 欄位
* 鍵結不可重複
* 鍵結不可跨板
* 鍵結不可跨主題

**Comment by MROS** [comment]
把要完成的具體回文功能條列描述一下，我看對應的 PR 已經滿大的了。
