### ISSUE TITLE
後端 API 裡的 ID 成員都改成 i64

### ISSUE THREAD

**Issue by david0u0** [carbon-bond/carbonbond#68]
struct 的成員寫 ID 會導致：

* 初始化時要從 i64 轉成 ID
* 查詢其它資訊時要從 ID 轉回 i64

好處則只有查詢 ID 時不用轉型。

綜上所述，改成 i64 應該會讓程式碼乾淨一點。

**Comment by david0u0** [comment]
@MROS  @jerry73204  你們覺得如何?

**Comment by MROS** [comment]
意思是說只有 rust 的 struct 改爲 i64 ，但 gql API 維持 ID 嗎
那改爲 i64 ，當轉換爲 graphql 的 field 的時候，是不是要轉一次？

**Comment by david0u0** [comment]
是，但觀察現在的api，轉 graphql field 的狀況皆為呼叫 id_fields，被控制在程式碼的特定部份。ID 轉 i64 的狀況則遍佈各處，造成很多囉嗦的寫法。
另外，未來處理 n+1 問題時應該會把那些 struct 改寫，很多 field 會變成 Option，因此這個 issue 應該到時候處理？

**Comment by MROS** [comment]
n + 1 問題跟 Option 的關係在哪裏？

**Comment by MROS** [comment]
不重要了，將遷至幾丁質
